from prompts import GENERAL, LOW_ENTROPY

EN_EXTRA = [
    "Write a blog post of about 250 words on how to keep a small garden alive during a heatwave.",
    "Write about 250 words describing what makes a good podcast host.",
    "Write a 250-word explainer on why bread rises, for curious home bakers.",
    "Write a 250-word piece about the appeal of night trains in Europe.",
    "Write about 250 words giving advice to a friend who wants to start journaling.",
    "Write a 250-word blog post about why some people love spreadsheets.",
    "Write a 250-word review of a fictional neighborhood ramen bar.",
    "Write about 250 words on how to prepare a dog for a long car trip.",
    "Write a 250-word reflection on the ritual of Sunday morning coffee.",
    "Write a 250-word explanation of how noise-cancelling headphones work, for non-engineers.",
    "Write about 250 words on the etiquette of group chats.",
    "Write a 250-word story about a bus driver who knows every passenger's name.",
    "Write a 250-word blog post about the case for taking a real lunch break.",
    "Write about 250 words describing a small-town summer festival.",
    "Write a 250-word explanation of why cats knead blankets.",
    "Write a 250-word piece about learning to swim as an adult.",
    "Write about 250 words giving advice to someone moving abroad for the first time.",
    "Write a 250-word blog post about the hidden work of restaurant dishwashers.",
    "Write a 250-word explanation of what makes a strong password and why.",
    "Write about 250 words on why board game nights make friendships stronger.",
    "Write a 250-word review of a fictional budget hiking backpack.",
    "Write a 250-word blog post about the joys of secondhand furniture.",
    "Write about 250 words describing the sounds of a city at 5 a.m.",
    "Write a 250-word explanation of how tides work, for children aged ten.",
    "Write a 250-word letter of encouragement to a nephew starting university.",
    "Write about 250 words on why people collect vinyl records.",
    "Write a 250-word blog post about the art of writing a good out-of-office message.",
    "Write a 250-word piece about volunteering at an animal shelter.",
    "Write about 250 words explaining how a small bookshop can compete with online giants.",
    "Write a 250-word explanation of jet lag and how to reduce it.",
    "Write a 250-word blog post about the case for walking meetings.",
    "Write about 250 words describing the perfect rainy-day movie afternoon.",
    "Write a 250-word story about a lost umbrella that travels across a city.",
    "Write a 250-word explanation of why leaves change color in autumn.",
    "Write about 250 words giving advice on hosting a dinner party on a budget.",
    "Write a 250-word blog post about the appeal of tiny houses.",
    "Write a 250-word review of a fictional language-learning app.",
    "Write about 250 words on the etiquette of borrowing books from friends.",
    "Write a 250-word explanation of how a bicycle stays upright.",
    "Write a 250-word piece about the last day of school, from a teacher's point of view.",
    "Write about 250 words on why people love true crime podcasts.",
    "Write a 250-word blog post about the case for repairing clothes instead of replacing them.",
    "Write a 250-word explanation of how sourdough starters work.",
    "Write about 250 words describing a chess club that meets in a park.",
    "Write a 250-word letter from a coach to a team after losing a final.",
    "Write a 250-word blog post about why cities need more benches.",
    "Write about 250 words explaining how to read a nutrition label.",
    "Write a 250-word piece about the smell of old libraries.",
    "Write a 250-word explanation of why the moon looks bigger near the horizon.",
    "Write about 250 words giving advice to someone starting a newsletter.",
    "Write a 250-word blog post about the underrated pleasure of doing nothing.",
    "Write a 250-word review of a fictional family-run bike repair shop.",
    "Write about 250 words on why houseplants make people happier.",
    "Write a 250-word explanation of how airports decide gate assignments, for travelers.",
    "Write a 250-word story about a lighthouse converted into a café.",
    "Write about 250 words on the etiquette of shared kitchens at work.",
    "Write a 250-word blog post about the case for learning to touch-type.",
    "Write a 250-word piece about a grandfather teaching his granddaughter to fish.",
    "Write about 250 words explaining why some songs get stuck in your head.",
    "Write a 250-word explanation of how recycling plants sort materials.",
    "Write a 250-word blog post about the joy of handwritten letters.",
    "Write about 250 words giving advice on choosing a first apartment.",
    "Write a 250-word review of a fictional community theater production.",
    "Write about 250 words describing the mood of a stadium before kickoff.",
    "Write a 250-word explanation of why we yawn.",
    "Write a 250-word blog post about the case for local newspapers.",
    "Write about 250 words on why people enjoy puzzles and crosswords.",
    "Write a 250-word piece about a market vendor who sells only tomatoes.",
    "Write a 250-word explanation of how weather forecasts are made, for a general audience.",
    "Write about 250 words giving advice to a teenager on managing screen time.",
]
assert len(EN_EXTRA) == 70
EN100 = GENERAL + EN_EXTRA

ES = [
    "Escribe una entrada de blog de unas 250 palabras sobre por qué dormir bien mejora la productividad.",
    "Escribe unas 250 palabras de opinión sobre el teletrabajo y su efecto en las ciudades.",
    "Escribe un artículo corto (unas 250 palabras) con consejos para alguien que empieza a correr.",
    "Escribe unas 250 palabras describiendo, en primera persona, un viaje memorable a un pueblo de costa.",
    "Explica en unas 250 palabras cómo decide un buscador qué páginas mostrar primero.",
    "Escribe una reseña de 250 palabras de una cafetera espresso de gama media.",
    "Escribe un texto de 250 palabras sobre por qué procrastinamos y cómo dejar de hacerlo.",
    "Escribe unas 250 palabras de consejos para que una panadería pequeña crezca en internet.",
    "Escribe un relato de 250 palabras sobre un farero que recibe una carta inesperada.",
    "Explica el interés compuesto en unas 250 palabras para adolescentes.",
    "Escribe una entrada de blog de 250 palabras sobre pros y contras de la bici eléctrica para ir al trabajo.",
    "Escribe unas 250 palabras sobre cómo prepararse para una entrevista en una startup.",
    "Escribe una reflexión de 250 palabras sobre por qué nos gustan las películas de terror.",
    "Escribe una guía de 250 palabras para elegir plantas de interior en un piso con poca luz.",
    "Escribe unas 250 palabras describiendo el ambiente de un mercado de agricultores un domingo.",
    "Escribe un artículo de 250 palabras sobre la historia y el atractivo de los juegos de mesa.",
    "Escribe unas 250 palabras explicando qué necesita una buena página de aterrizaje.",
    "Escribe una carta de 250 palabras de una abuela a su nieto sobre la paciencia.",
    "Escribe una entrada de blog de 250 palabras sobre las ventajas y desventajas de cocinar en lote.",
    "Explica en 250 palabras por qué el cielo cambia de color al atardecer, para público general.",
    "Escribe un texto motivador de 250 palabras para adultos que aprenden un segundo idioma.",
    "Escribe unas 250 palabras sobre cómo decide una redacción qué va en portada.",
    "Escribe una reseña de 250 palabras de un videojuego indie imaginario sobre jardinería.",
    "Explica en 250 palabras cómo entrenan las vacunas al sistema inmunitario.",
    "Escribe unas 250 palabras sobre la etiqueta de trabajar desde cafeterías.",
    "Escribe una entrada de blog de 250 palabras sobre el minimalismo y tener menos cosas.",
    "Escribe un texto de 250 palabras sobre una tarde de lluvia en una librería de segunda mano.",
    "Explica en 250 palabras por qué las ciudades son más calurosas que el campo.",
    "Escribe unas 250 palabras de consejos para negociar el alquiler con el casero.",
    "Escribe una entrada de blog de 250 palabras sobre las alegrías y frustraciones de aprender a cocinar.",
    "Escribe unas 250 palabras sobre cómo mantener vivo un huerto pequeño durante una ola de calor.",
    "Escribe unas 250 palabras sobre qué hace bueno a un presentador de pódcast.",
    "Explica en 250 palabras por qué sube el pan, para panaderos caseros curiosos.",
    "Escribe unas 250 palabras sobre el encanto de los trenes nocturnos en Europa.",
    "Escribe unas 250 palabras de consejos para un amigo que quiere empezar a escribir un diario.",
    "Escribe una entrada de blog de 250 palabras sobre por qué a algunas personas les encantan las hojas de cálculo.",
    "Escribe una reseña de 250 palabras de un bar de ramen imaginario de barrio.",
    "Escribe unas 250 palabras sobre cómo preparar a un perro para un viaje largo en coche.",
    "Escribe una reflexión de 250 palabras sobre el ritual del café del domingo por la mañana.",
    "Explica en 250 palabras cómo funcionan los auriculares con cancelación de ruido, para no ingenieros.",
]
assert len(ES) == 40

LONG = [
    "Write a detailed blog article of about 800 words, with an introduction, four subheadings and a conclusion, on how to plan a two-week trip to Japan on a budget.",
    "Write an 800-word explainer, with subheadings, on how compound interest, inflation and index funds interact for a first-time investor.",
    "Write an 800-word article, with subheadings, about the history of the bicycle and how it changed cities.",
    "Write an 800-word guide, with subheadings, to starting a vegetable garden on a balcony.",
    "Write an 800-word opinion essay, with subheadings, on whether remote work is good for young professionals.",
    "Write an 800-word article, with subheadings, on how search engines rank pages, written for small business owners.",
    "Write an 800-word feature, with subheadings, about a day in the life of a lighthouse keeper in the 1950s.",
    "Write an 800-word explainer, with subheadings, on how vaccines are developed and tested.",
    "Write an 800-word guide, with subheadings, to preparing for a first marathon over six months.",
    "Write an 800-word article, with subheadings, on the science of sleep and practical habits for better rest.",
    "Write an 800-word essay, with subheadings, on why people procrastinate and evidence-based ways to stop.",
    "Write an 800-word article, with subheadings, about how a small independent bookshop can thrive today.",
    "Write an 800-word explainer, with subheadings, on how the electricity grid balances supply and demand.",
    "Write an 800-word guide, with subheadings, to hosting a memorable dinner party for eight on a budget.",
    "Write an 800-word article, with subheadings, on the appeal of board games and how to build a game night group.",
    "Write an 800-word feature, with subheadings, about the culture of neighborhood coffee shops.",
    "Write an 800-word explainer, with subheadings, on how weather forecasts are made and why they are sometimes wrong.",
    "Write an 800-word guide, with subheadings, to negotiating a job offer at a startup.",
    "Write an 800-word article, with subheadings, on urban heat islands and what cities can do about them.",
    "Write an 800-word essay, with subheadings, on the joys and frustrations of learning to cook as an adult.",
]
assert len(LONG) == 20

SETS = {
    "en":   {"prompts": EN100, "max_new": 300, "lang": "en"},
    "low":  {"prompts": LOW_ENTROPY, "max_new": 300, "lang": "en"},
    "es":   {"prompts": ES, "max_new": 300, "lang": "es"},
    "long": {"prompts": LONG, "max_new": 1100, "lang": "en"},
}
